[package]
name = "txrse"
version = "0.1.1"
edition = "2021"

[dependencies]
uesave = "0.6.1"
clap = { version = "4.5.27", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }

[profile.release]
strip = true